name: Build and deploy to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
        env:
          CI: false

