name: Build and deploy to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-push-tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Build with npm
        env:
          CI: false
        run: | 
            npm install
            npm ci
            npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

